- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/pages/Deshbord.tsx
- client/src/types/BannerInterface.ts
- client/src/types/UserInterface.ts
> {add} deshbird pege

- client/package-lock.json
- client/package.json
- client/src/App.tsx
- client/src/components/ErrorPage.tsx
- client/src/components/LoginForm.tsx
- client/src/pages/AllBanners.tsx
- client/src/pages/BannerByProducdID.tsx
- client/src/pages/BannerCreateOrEdit.tsx
- client/src/pages/Banners.tsx
- client/src/pages/CategoryByName.tsx
- client/src/pages/HomePage.tsx
- client/src/pages/Login.tsx
- client/src/pages/Register.tsx
- client/src/routes/Routs.tsx
יצרתי ראוטר ועמודים והבאתי סקיצה של לוגאין מהפרויקט
> Pinchas dey 1

- client/package-lock.json
- client/package.json
- client/src/components/loginANDregister/LoginForm.tsx
- client/src/components/loginANDregister/RegisterForm.tsx
- client/src/pages/Deshbord.tsx
- client/src/pages/Login.tsx
- client/src/pages/Register.tsx
סידור עמוד לוגין והרשמה בצד לקוח
> Arrangement of a login and registration page on the client side

- client/src/App.tsx
- client/src/components/CardBanner.tsx
- server/src/models/bannersModel.ts
- server/src/server.ts
יצרתי כרטיס לבאנר (לענ"ד קצת מיותר) יש כפתורי-אייקון של מחיקה ועריכה, הוספתי גם לכרטיס מוצר כפתור-אייקון של הוספה. נכון לעכשיו כל כפתורי האייקון לא מפעילים שום דבר
> (add) CardBanner but BUttonIcons dosent work

- client/src/App.tsx
- client/src/api/bannersImageFunc.ts
- client/src/components/Header.tsx
- client/src/components/ManageIcon.tsx
- client/src/components/SidBar.tsx
- client/src/components/StatusLogsAndCart.tsx
- client/src/components/loginANDregister/LoginForm.tsx
- client/src/pages/Deshbord.tsx
header and basic sidebar and logout function
> header and sidebar and logout

- server/jest.config.js
- server/package-lock.json
- server/package.json
- server/src/__tests__/routes/user.routes.test.ts
- server/src/__tests__/server.test.ts
- server/src/middleware/auth-middleware.ts
סוף סוף... התחלתי עם הבדיקות, האנגפוינט להשיג את כל הבאנרים עובד השאר כנראה לא. אמשיך בעז"ה שבוע הבא
> (add) 1 test pass, other fail

- client/src/components/Tables/ProductTable.tsx
- client/src/components/Tables/UserTable.tsx
הוספתי את שתי הטבלאות - מוצרים ומשתמשים
> (add) prodacts table, users table

- Jenkinsfile
> Update Jenkinsfile with Docker agent configuration

- Jenkinsfile
> Refactor Jenkinsfile to run npm commands in Docker

- Jenkinsfile
> Refactor Jenkinsfile to add post-build

- Jenkinsfile
> Add npm install step and update post-build

- Jenkinsfile
> Disable GitHub push trigger and enable GitHub pull

- Jenkinsfile
> Commented out the githubPush trigger in

- Jenkinsfile
> Update Jenkinsfile to echo "test test2" instead of

- Jenkinsfile
> Update Jenkinsfile to echo "test test test"

- Jenkinsfile
> Update Jenkinsfile to echo "test test" instead of

- Jenkinsfile.test
> Update Jenkinsfile.test with separate stages for

- Jenkinsfile.test
installation and testing of client and server
> Refactor Jenkinsfile.test to parallelize

- Jenkinsfile.test
> Refactor Jenkinsfile.test to install and test

- Jenkinsfile.test
> Refactor Jenkinsfile.test to improve script

- Jenkinsfile
> Remove GitHub pull request trigger from
